### ISSUE TITLE
[Minor] - Defaults kwargs for dispersion env changed - Might result in different performance results

### ISSUE THREAD

**Issue by KaleabTessera** [proroklab/VectorizedMultiAgentSimulator#144]
When this [commit](https://github.com/proroklab/VectorizedMultiAgentSimulator/commit/6bf27db51655d22dd78ed223c3767d761367c4ab#diff-aefaa1f0aa23ffd9bc65444c52276a93e666b89e83bf74c5287b78d4e44c369cL37) was made the defaults for `food_radius` in dispersion was changed from 0.02 to 0.05. Might make minor performance differences for people using the default setting.

**Comment by matteobettini** [comment]
Hello! Yeah you are right, I think I was a bad person back then :( 

Nowadays I would be way more careful about it.

Do you think there is something we can do to make it better? I don't know if reverting will improve the situation...

**Comment by matteobettini** [comment]
Sometimes some scenarios get major bc-breaking refactoring between versions, it will soon happen to football which is getting a LOT of new features and redesigns.

What i can do now is tag each commit that breaks old params with the bc-breaking tag and list the bc-breaking stuff in the version info. so that users that want to check if bc-breaking changes happened to their scenarios in newer vmas versions can look there.

**Comment by KaleabTessera** [comment]
Sounds like a good idea! @matteobettini You could also add a section in the release docs of which envs have breaking changes. Sometimes core dynamics get changed, and it hard to know if it will influence the env you are using.

**Comment by matteobettini** [comment]
> Sounds like a good idea! @matteobettini You could also add a section in the release docs of which envs have breaking changes. Sometimes core dynamics get changed, and it hard to know if it will influence the env you are using.

I will! I'll keep an extra eye out for bc-breaking PRs and add them to the release notes.

We are currently having high-priority on not making bc-breaking changes so hopefully vmas will be a bit more stable in the future
