### ISSUE TITLE
Differentiability of rewards

### ISSUE THREAD

**Issue by maxhuettenrauch** [proroklab/VectorizedMultiAgentSimulator#25]
While testing some stuff, I was wondering whether there is a straightforward way to obtain differentiable rewards, since everything is written in pytorch. Currently, the rewards is not if I'm not mistaken.

**Comment by matteobettini** [comment]
Hello,

So, the simulator has not been designed to be fully differentiable.

As you said, since the inputs on each steps are tensors (actions) and the outputs are also tensors (obtained by some torch processing of the input), there might be an easy way to make it differentiable. But we have not investigated this yet.

**Comment by maxhuettenrauch** [comment]
I see. I tried, but the in place operations are making things difficult.

Anyways, thanks a lot for the library :)
