### ISSUE TITLE
Simulator running slower on GPU

### ISSUE THREAD

**Issue by junkdood** [proroklab/VectorizedMultiAgentSimulator#26]
HI! I am trying to use this simulator after reading the paper. However, when I was running `VectorizedMultiAgentSimulator/vmas/examples/use_vmas_env.py`, I got some weird results.
```
It took: 302.1871528625488s for 100 steps of 10000 parallel environments on device cpu for RLLIB wrapped simulator
It took: 933.8081917762756s for 100 steps of 10000 parallel environments on device cuda for RLLIB wrapped simulator
```
It seems that the simulator running slower on GPU. Is this result reasonable?
I was running VMAS on my laptop with RTX3060.

**Comment by matteobettini** [comment]
Try downloading the latest version of VMAS and setting `wrapper = None`. The RLlib wrapper you are using cannot use the GPU for feeding actions to environments.  This is because RLlib forces the `VectorEnv` interface to use lists (which are not tensors). Let me know what results you get with no Wrapper, mine are:

```
It took: 128.2031557559967s for 100 steps of 10000 parallel environments on device cpu for simulator 
It took: 62.900607109069824s for 100 steps of 10000 parallel environments on device cuda for simulator  
```

**Comment by junkdood** [comment]
Thanks! It works.

**Comment by Zartris** [comment]
I know it is close, but is the version on pip the newest one? 
Because mine seems to be much worse on GPU, even with the `wrapper = None`
