### ISSUE TITLE
Action options for agents

### ISSUE THREAD

**Issue by menichel** [proroklab/VectorizedMultiAgentSimulator#34]
Hi all,

I read your [paper](http://arxiv.org/abs/2207.03530) and got very interested in the library. As far as I understood, the library only supports forces as action-space for the agents, right? I would also be interested in controlling the agent orientation and also have only a kinematic environment to speed up training even further. Since the last commit and the paper release, was the orientation control added and is there the possibility not to consider forces but only linear an angular velocities?

Thank you for the info.

Kind regards,

menichel

**Comment by matteobettini** [comment]
Hello,

Thanks for the interest!

There is now support for both the features you ask.

For orientation control you have to set u_rot_range at agent creation time (https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/simulator/core.py#L704) which is the range of the torque action. The action space will then automatically have an extra action for rotations (both discrete and continuous).

For velocity actions, you can use a velocity controller in a preprocess_action phase. It is not gonna speed up simulation but it allows you to input velocities.

See more info int the last 2 bullet points of this https://github.com/proroklab/VectorizedMultiAgentSimulator#simulator-features

Best

-----------
Matteo Bettini
PhD Candidate in Computer Science
Website<https://matteobettini.com/> | ProrokLab<https://www.proroklab.org/> | GitHub<https://github.com/MatteoBettini> | Linkedin<https://www.linkedin.com/in/matteo-bettini-mb/>
Department of Computer Science and Technology
University of Cambridge
William Gates Building | 15 JJ Thomson Avenue | Cambridge CB3 0FD, UK

From: menichel ***@***.***>
Date: Tuesday, 17 January 2023 at 15:00
To: proroklab/VectorizedMultiAgentSimulator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [proroklab/VectorizedMultiAgentSimulator] Action options for agents (Issue #34)

Hi all,

I read your paper<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Farxiv.org%2Fabs%2F2207.03530&data=05%7C01%7Cmb2389%40universityofcambridgecloud.onmicrosoft.com%7Ca4fb513146e24748c6f008daf89b97a5%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638095644394761913%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bHkR7JeQqo5V%2F3bDULJQ9%2BGdcv%2FMVHRKCAz9A%2BZ%2BLyw%3D&reserved=0> and got very interested in the library. As far as I understood, the library only supports forces as action-space for the agents, right? I would also be interested in controlling the agent orientation and also have only a kinematic environment to speed up training even further. Since the last commit and the paper release, was the orientation control added and is there the possibility not to consider forces but only linear an angular velocities?

Thank you for the info.

Kind regards,

menichel
