### ISSUE TITLE
[Issue] Inconsistent Agent Names

### ISSUE THREAD

**Issue by EdanToledo** [proroklab/VectorizedMultiAgentSimulator#41]
There seems to be inconsistencies in the naming convention of agents. Certain scenarios name agents as "Agent {n}" and others name as "Agent_{n}". Its not a huge issue but when writing a wrapper for other frameworks this can cause trouble.

**Comment by matteobettini** [comment]
Thanks edan!

I'll get to this as soon as i can.

Anyway I think that wrappers should use entity names. 
Each agent can be indexed by its unique index identifier in world.agents list.

This because agent in scenarios can have arbitrary names (as you pointed out).
These could be agent_0,1,2 or "mario" , "luigi" or "prey", "predator".

**Comment by EdanToledo** [comment]
I see, thank you. I was using the dict_spaces interface but I realised that there was a mistake I was performing that caused the inconsistencies to be a hiccup.
