### ISSUE TITLE
Request: continuous communication examples

### ISSUE THREAD

**Issue by Zartris** [proroklab/VectorizedMultiAgentSimulator#44]
Hi 
First of all, this is not a bug in your code. I am looking into your simulator again to determine if this is what I should use for my next research project.

I was looking into the communication aspect of this simulator. I do see some examples of discrete communication (in the MPE folder), and I know how to expand this into only local communication. However, I do not see any continuous communication examples. 
How would you do this with the current architecture?

**Comment by matteobettini** [comment]
Hello,

So, comminucation works like this:

The simulator provides support for communication as an action (continuous or discrete) this can be obtained by setting a dim_c when creating a world. The communication action will be added to the action space and to the agent state.
To set it continuous just set `continuous_actions=True`. 

To achieve communication in the policy (so that agents see an obs, communicate, and take an action after communication) this is not part of vmas. Vmas is only interested in giving you observation and getting actions, so what you do in the middle is external.

In our lab to do communication in the policies we use GNNs, here are examples of how we train this in vmas https://github.com/proroklab/HetGPPO

**Comment by Zartris** [comment]
I misunderstood continuous communication as, if I understand you correctly, continuous here means the values sent through the channel (floats or doubles). Where what I understood is continuous time communication meaning you take into consideration how much information can be sent at a given time and meaning you would send messages as a stream instead of whole messages at each timestep. 
But I understand what you mean now, thanks.
