### ISSUE TITLE
[Feature] Customize step function

### ISSUE THREAD

**Issue by Jianye-Xu** [proroklab/VectorizedMultiAgentSimulator#64]
As can be seen from the [`scenario.py` file](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/simulator/scenario.py), we can customize the following functions: 
- `make_world`
- `reset_world_at`
- `observation`
- `reward`
- `done`
- `info`
- `extra_render`
- `process_action`

Is it possible to define a customized `step` function?
The reason is that my agents have dynamics that are not available in the library. The actions are not physical variables (neither force nor torque) but discrete integers, which abstract the physical inputs. Therefore, I need to customize the `step` function, which tells the environment how to update agent states.

If customizing the `step` function is not currently allowed, is there a workaround for my usage? 

I am looking forward to your reply. Thanks!

**Comment by matteobettini** [comment]
Hello, thanks for opening the issue.

As of now, writing a custom step is not supported, but here are some things that could help your usecase:
- vmas actions are 2 (or 3) dimensions for physical actions and any dimension for communication actions. they are automatically set in `agent.action.u` and `agent.action.c`. There values are available to the `process_action` function which can manipulate them as you like for the simulator step. Thus, I usually envisioned to put custom dynamics in that function if possible (that is what we do for the velocity controller and the differential drive). I agree that this constraint is unideal and we are planning to allow any number of actions in the future #51. 
- a workaround would be to use the communication actions to represent the actions you need and compute the dynamics to get forces in `process_action`
- otherwise you can overwrite the world step function in your VMAS fork

If you have any other suggestion let me know

**Comment by Jianye-Xu** [comment]
Hello @matteobettini,

Thanks for your detailed explanation of a workaround. However, given that the real actions in my case (navigating mobile robots) are target values for steering angle and acceleration instead of physical forces (a low-level controller takes care of eliminating tracking errors), I think I am unable to do what you suggested if I understand you correctly.

Currently, I do not think that I have a better suggestion than supporting a customized `step` function.

Best regards,
Jianye Xu

**Comment by matteobettini** [comment]
Let me understand your need a little bit better.

- What are the dynamics of your robot? Differential drive?
- If I understand you would like to have a reference angle and a reference accelleration as input actions. Is that correct?

Here are some things that could help:

- we have an example scenario on how to control a differential drive robot https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/debug/diff_drive.py and the dynamics for this agent are here https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/simulator/dynamics/diff_drive.py
- we have an example scenario on how to control a robot with velocity actions instead of forces here https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/debug/vel_control.py with the controller here https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/simulator/controllers/velocity_controller.py

**Comment by Jianye-Xu** [comment]
Hello,

Thanks for the links. 

For a quick understanding of my case, this is my previous work (https://www.youtube.com/watch?v=1LUDNEKFImg), in which an MPC is used to plan trajectories for multiple car-like robots. And now I want to use RL to control them. Here are some key points:
- Each robot has the shape of a **rectangle**.
- The dynamics of each robot are modeled by the widely used **kinematic bicycle model** (not the differential drive model).
- The control inputs (and thus the actions) are **steering angle** and **speed** (or **angular velocity** and **acceleration**).

Based on the links you kindly provided, I do see a possibility to benefit from this repo for my research. However, some of my remaining questions are:
- Given that velocity is supported as an action, can I additionally add steering angle as another action to change the rotations (also called the yaw angle) of the robots?
- It seems that the kinematic bicycle model is not supported yet. Is this a desired feature for this repo? i.e., I may be glad to contribute to it and also add this scenario (navigating multiple mobile robots) to this repo if I can eventually use this repo for my case.

**Comment by matteobettini** [comment]
I understand better now thanks! Very cool use case, would love to see it in VMAS.

> Given that velocity is supported as an action, can I additionally add steering angle as another action to change the rotations (also called the yaw angle) of the robots?

Yes, have a look at the differential drive examples linked. There we have an action for force and one for torque. You can potentially have any actions you want. The constraint is that the physics step will expect 2d forces and torque so as long as you translate your input in that format it is fine.




> It seems that the kinematic bicycle model is not supported yet. Is this a desired feature for this repo? i.e., I may be glad to contribute to it and also add this scenario (navigating multiple mobile robots) to this repo if I can eventually use this repo for my case.

We would love any contribution and new dynamics model would be amazing. The bycicle model would be much appreciated as a contirbution. 

Don't esitate to open PRs or issues, I would be happy to help.

**Comment by Jianye-Xu** [comment]
I am happy to hear that this use case would be of value to VMAS and thanks for the answers. With what you said, I will invest time in creating my use case using VMAS. Once done, I will open PRs. If I encounter any difficulties or problems, I will let you know.

**Comment by Jianye-Xu** [comment]
The kinematic bicycle model is implemented in pull request #68. @matteobettini

**Comment by matteobettini** [comment]
Fantastic! Closing this issue and moving the discussion there
