### ISSUE TITLE
[Issue] Unmatched action size for kinematic bicycle model and differential drive robots

### ISSUE THREAD

**Issue by Jianye-Xu** [proroklab/VectorizedMultiAgentSimulator#75]
# Issue Description
PR #68 introduces the kinematic bicycle model, which has two inputs: velocity (or acceleration) and steering (or rotation). However, for a 2D world, assuming there is no communication action, the function `get_agent_action_size()` (see below) defined in [environment.py](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/simulator/environment/environment.py#L293C24-L293C24) will return 3 (2 for position and 1 for rotation) instead of 2 as the action size, which does not meet the truth, since 2 actions already suffice to control an agent with the dynamics of the kinematic bicycle model. This can be verified if we look closely into the kinematic bicycle model ([this line](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/127a9ec98a46f4e9dfa079d15ea3c878a682dd3f/vmas/simulator/dynamics/kinematic_bicycle.py#L58), where only the first entry is used). I think this issue applies also to differential drive robots, which can be controlled through 2 actions but 3 will be returned as the action size.
 
```
def get_agent_action_size(self, agent: Agent):
    return (
        self.world.dim_p
        + (1 if agent.action.u_rot_range != 0 else 0)
        + (self.world.dim_c if not agent.silent else 0)
        if self.continuous_actions
        else 1
        + (1 if agent.action.u_rot_range != 0 else 0)
        + (1 if not agent.silent else 0)
    )
```
# My Case
I am trying to use [MAPPO](https://pytorch.org/rl/tutorials/multiagent_ppo.html) with my own customized scenario where all agents feature the dynamics of the kinematic bicycle model. However, if I run this print:
```
>>> print("action_spec:", env.full_action_spec)
action_spec: CompositeSpec(
    agents: CompositeSpec(
        action: BoundedTensorSpec(
            shape=torch.Size([60, 6, 3]),
            space=ContinuousBox(
                low=Tensor(shape=torch.Size([60, 6, 3]), device=cpu, dtype=torch.float32, contiguous=True),
                high=Tensor(shape=torch.Size([60, 6, 3]), device=cpu, dtype=torch.float32, contiguous=True)),
            device=cpu,
            dtype=torch.float32,
            domain=continuous), device=cpu, shape=torch.Size([60, 6])), device=cpu, shape=torch.Size([60]))
```
, where `shape=torch.Size([60, 6, 3])` indicates that there are 60 vectorized environments, 6 agents, and each agent has 3 actions. This automatically leads to the policy network of each agent having an output size of 6:

```
>>> print("policy_net:", policy_net)
policy_net: Sequential(
  (0): MultiAgentMLP(
    (agent_networks): ModuleList(
      (0): MLP(
        (0): Linear(in_features=43, out_features=256, bias=True)
        (1): Tanh()
        (2): Linear(in_features=256, out_features=256, bias=True)
        (3): Tanh()
        (4): Linear(in_features=256, out_features=6, bias=True)
      )
    )
  )
  (1): NormalParamExtractor()
)
```
. Note that the reason for `out_features=6` (instead of `out_features=3`) is that PPO uses a stochastic policy and thus the policy network outputs two values (mean and standard deviation of the normal distribution) for each action. However, two out of the 6 outputs are useless as they do not contribute to the movement of agents. 

I would highly appreciate it if you would have some comments on this issue. It would be indeed helpful if you would have a workaround for me. If I could provide any further information, please let me know.

**Comment by matteobettini** [comment]
Hello!

Thanks for posting this, I am glad to have a chance to talk about it and discuss how we can improve it.

The main reason is backwards-compatibility. Originally vmas just had 2 physical actions (2d forces), there actions have the associated `u_range` and `u_multiplier`. 

When rotation actions where introduced, they were added as a third action, with its own `u_rot_range` and `u_rot_multiplier`. 

A vmas agent is then allowed max 3 actions (for now) which correspond to 2 actions for movement and one for rotation.

The dynamics models of the car and diff_drive only need 2 input actions (one movement and one rotation). If these were gathered from the first 2 actions, it would not be possible to set different ranges and multipliers for translation and rotation.

Therefore, the current way they work is that they take 3 actions but the second is ignored. 

To fix this, we would need to let each agent have its action space property, so that it can be modified by the dynamics. SInce we are doing this, it would also be usefull to detach the physical meaning from agent actions and allow users to define any number of actions which they can then process as they like #51.

This change will be bc-breaking as `u_rot_range`, `u_rot` and `u_rot_multiplier` would be removed. In ther place users will just be able to ask for how many actions they want and their range and multiplers.

**Comment by matteobettini** [comment]
I will work on a PR for this and #51 and ping you
